"""
bot/recall_client.py — Recall.ai API client for Quorum.

Handles all communication with the Recall.ai REST API: joining meetings,
sending chat messages, injecting audio, and leaving calls.

All methods are async using httpx. Never raises — every method catches its
own exceptions and returns a safe value so the bot never crashes on an API
hiccup.
"""

import asyncio
import base64
import logging
import os
import traceback
from typing import Any

import httpx
from dotenv import load_dotenv

from bot import BotStatus

load_dotenv()

logger = logging.getLogger(__name__)

_RECALL_BASE_URL = "https://us-west-2.recall.ai/api/v1"
_COMPANION_URL = os.getenv("COMPANION_URL", "").strip()
_REQUEST_TIMEOUT = 15.0  # seconds


class RecallClient:
    """
    Async client for the Recall.ai bot API.

    Every public method is safe to call without a try/except — all
    exceptions are caught internally, logged with full traceback, and
    a safe fallback value is returned.
    """

    def __init__(
        self,
        api_key: str,
        webhook_base_url: str,
        bot_name: str,
    ) -> None:
        """
        Initialise the Recall.ai client.

        Args:
            api_key:           Recall.ai API key.
            webhook_base_url:  Public base URL for webhooks (ngrok URL in dev).
                               Recall.ai will POST transcript events here.
            bot_name:          Display name shown in the meeting.
        """
        self._api_key = api_key
        self._webhook_base_url = webhook_base_url.rstrip("/")
        self._bot_name = bot_name
        self._headers = {
            "Authorization": f"Token {api_key}",
            "Content-Type": "application/json",
        }
        logger.info(
            "RecallClient initialised — webhook=%s bot_name=%s",
            self._webhook_base_url,
            self._bot_name,
        )

    # ── Public methods ────────────────────────────────────────────────────────

    async def join_meeting(
        self, meeting_url: str, meeting_id: str
    ) -> BotStatus:
        """
        Send a bot to a meeting and configure real-time transcription.

        The bot will:
        - Start streaming transcripts to /webhook/transcript immediately.
        - Send a chat message with the companion app link on join.

        Args:
            meeting_url: Full Google Meet / Zoom / Teams URL.
            meeting_id:  Unique session ID generated by main_bot.py.

        Returns:
            BotStatus with status "joining" on success, "error" on failure.
        """
        # Recall.ai new API uses WebSocket for real-time transcripts.
        # The ngrok URL is reused — ngrok tunnels wss:// automatically.
        transcript_ws = self._webhook_base_url.replace("https://", "wss://").replace("http://", "ws://")
        transcript_ws = f"{transcript_ws}/ws/transcript"
        status_webhook = f"{self._webhook_base_url}/webhook/bot_status"
        companion_link = f"{_COMPANION_URL}/m/{meeting_id}".strip()
        # Recall.ai blocks localhost URLs in payloads — only include companion
        # link if it's a real public URL, not localhost.
        is_public_companion = companion_link.startswith("https://")
        join_message = f"Hi, I am {self._bot_name}."
        if is_public_companion:
            join_message += f" Follow along here: {companion_link}"

        payload: dict[str, Any] = {
            "bot_name": self._bot_name,
            "meeting_url": meeting_url,
            "recording_config": {
                "transcript": {
                    "provider": {
                        "deepgram_streaming": {
                            "api_key": os.getenv("DEEPGRAM_API_KEY", "").strip(),
                            "model": "nova-2",
                            "language": "en-US",
                            "diarize": "true",
                            "smart_format": "true",
                            "interim_results": "true",
                        }
                    }
                },
                "realtime_endpoints": [
                    {
                        "type": "websocket",
                        "url": transcript_ws,
                        "events": ["transcript.data"],
                    }
                ],
            },
            "status_change_webhook_url": status_webhook,
            "chat": {
                "on_bot_join": {
                    "send_to": "everyone",
                    "message": join_message,
                }
            },
        }

        try:
            async with httpx.AsyncClient(
                timeout=_REQUEST_TIMEOUT, headers=self._headers
            ) as client:
                resp = await client.post(
                    f"{_RECALL_BASE_URL}/bot/", json=payload
                )
                resp.raise_for_status()
                data = resp.json()

            bot_id = data.get("id", "unknown")
            logger.info(
                "Bot joining meeting — bot_id=%s meeting_id=%s url=%s",
                bot_id,
                meeting_id,
                meeting_url,
            )
            return BotStatus(
                meeting_id=meeting_id,
                status="joining",
                bot_id=bot_id,
                meeting_url=meeting_url,
                joined_at=None,
            )

        except Exception:
            logger.error(
                "join_meeting failed:\n%s", traceback.format_exc()
            )
            return BotStatus(
                meeting_id=meeting_id,
                status="error",
                bot_id="",
                meeting_url=meeting_url,
                joined_at=None,
            )

    async def send_chat_message(self, bot_id: str, message: str) -> bool:
        """
        Send a chat message from the bot into the meeting.

        Args:
            bot_id:  Recall.ai bot UUID.
            message: Text to send to all participants.

        Returns:
            True on success, False on any failure.
        """
        try:
            async with httpx.AsyncClient(
                timeout=_REQUEST_TIMEOUT, headers=self._headers
            ) as client:
                resp = await client.post(
                    f"{_RECALL_BASE_URL}/bot/{bot_id}/send_chat_message/",
                    json={"message": message},
                )
                resp.raise_for_status()
            logger.info("Chat message sent via bot %s: %r", bot_id, message[:60])
            return True

        except Exception:
            logger.error(
                "send_chat_message failed for bot %s:\n%s",
                bot_id,
                traceback.format_exc(),
            )
            return False

    async def inject_audio(self, bot_id: str, audio_bytes: bytes) -> bool:
        """
        Inject MP3 audio bytes into the meeting as Quorum's voice.

        The audio is base64-encoded and sent to Recall.ai's output_audio
        endpoint, which plays it through the bot's microphone.

        Args:
            bot_id:      Recall.ai bot UUID.
            audio_bytes: Raw MP3 audio bytes from ElevenLabs.

        Returns:
            True on success, False on any failure. Never raises.
        """
        try:
            encoded = base64.b64encode(audio_bytes).decode("utf-8")
            async with httpx.AsyncClient(
                timeout=_REQUEST_TIMEOUT, headers=self._headers
            ) as client:
                resp = await client.post(
                    f"{_RECALL_BASE_URL}/bot/{bot_id}/output_audio/",
                    json={"kind": "mp3", "b64_data": encoded},
                )
                resp.raise_for_status()
            logger.debug("Audio injected — bot=%s bytes=%d", bot_id, len(audio_bytes))
            return True

        except Exception:
            # NEVER raise from inject_audio — a failed TTS injection should
            # not crash the bot or the transcription pipeline.
            logger.error(
                "inject_audio failed for bot %s:\n%s",
                bot_id,
                traceback.format_exc(),
            )
            return False

    async def leave_meeting(self, bot_id: str) -> bool:
        """
        Remove the bot from the meeting.

        Args:
            bot_id: Recall.ai bot UUID.

        Returns:
            True on success, False on failure.
        """
        try:
            async with httpx.AsyncClient(
                timeout=_REQUEST_TIMEOUT, headers=self._headers
            ) as client:
                resp = await client.post(
                    f"{_RECALL_BASE_URL}/bot/{bot_id}/leave_call/"
                )
                resp.raise_for_status()
            logger.info("Bot %s left the meeting", bot_id)
            return True

        except Exception:
            logger.error(
                "leave_meeting failed for bot %s:\n%s",
                bot_id,
                traceback.format_exc(),
            )
            return False

    async def get_bot_status(self, bot_id: str) -> BotStatus:
        """
        Fetch the current lifecycle status of a bot from Recall.ai.

        Args:
            bot_id: Recall.ai bot UUID.

        Returns:
            BotStatus reflecting the current state, or status="error" on failure.
        """
        try:
            async with httpx.AsyncClient(
                timeout=_REQUEST_TIMEOUT, headers=self._headers
            ) as client:
                resp = await client.get(f"{_RECALL_BASE_URL}/bot/{bot_id}/")
                resp.raise_for_status()
                data = resp.json()

            # Map Recall.ai status strings to our internal status labels
            raw_status = (
                data.get("status_changes", [{}])[-1]
                .get("code", "unknown")
                if data.get("status_changes") else "unknown"
            )
            status_map = {
                "joining_call": "joining",
                "in_call_not_recording": "active",
                "in_call_recording": "active",
                "call_ended": "left",
                "done": "left",
                "fatal": "error",
                "unknown": "active",
            }
            status = status_map.get(raw_status, "active")

            meeting_url = data.get("meeting_url", "")
            logger.debug("Bot %s status: %s (raw: %s)", bot_id, status, raw_status)

            return BotStatus(
                meeting_id=data.get("metadata", {}).get("meeting_id", ""),
                status=status,
                bot_id=bot_id,
                meeting_url=meeting_url,
                joined_at=None,
            )

        except Exception:
            logger.error(
                "get_bot_status failed for bot %s:\n%s",
                bot_id,
                traceback.format_exc(),
            )
            return BotStatus(
                meeting_id="",
                status="error",
                bot_id=bot_id,
                meeting_url="",
                joined_at=None,
            )


# ── Standalone test ───────────────────────────────────────────────────────────

async def _run_test() -> None:
    """
    Live integration test — joins a real meeting and leaves after 10 seconds.

    Requires RECALL_API_KEY, WEBHOOK_BASE_URL, BOT_NAME in .env.
    Prompts for a Google Meet URL.
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)-8s %(name)s — %(message)s",
    )

    api_key = os.getenv("RECALL_API_KEY", "").strip()
    webhook_url = os.getenv("WEBHOOK_BASE_URL", "").strip()
    bot_name = os.getenv("BOT_NAME", "Quorum").strip()

    if not api_key:
        print("[ERROR] RECALL_API_KEY not set in .env")
        return

    client = RecallClient(
        api_key=api_key,
        webhook_base_url=webhook_url,
        bot_name=bot_name,
    )

    meeting_url = input("Paste your Google Meet URL: ").strip()
    if not meeting_url:
        print("[ERROR] No URL provided — exiting")
        return

    meeting_id = "test-recall-001"

    print(f"\nJoining {meeting_url} ...")
    status = await client.join_meeting(meeting_url, meeting_id)
    print(f"bot_id : {status.bot_id}")
    print(f"status : {status.status}")

    if status.status == "error" or not status.bot_id:
        print("[ERROR] Failed to join — check your API key and URL")
        return

    print("\nWaiting 10 seconds before checking status...")
    await asyncio.sleep(10)

    current = await client.get_bot_status(status.bot_id)
    print(f"Current status after 10s: {current.status}")

    # MOCK — replace with real API call
    # send_chat_message is live but requires the bot to be in_call
    # await client.send_chat_message(status.bot_id, "Test message from Quorum")

    print("\nLeaving meeting...")
    left = await client.leave_meeting(status.bot_id)
    print(f"Left successfully: {left}")


def test() -> None:
    """Entry point for direct module execution."""
    asyncio.run(_run_test())


if __name__ == "__main__":
    test()
