import { QuorumCard } from "./types";

export const MOCK_CARDS: QuorumCard[] = [
  {
    id: "card-1",
    event_type: "context_surfaced",
    source: "github",
    title: "PR #247: Fix auth middleware token validation",
    summary: "Merged 2 days ago by @sarah. Changed OAuth token validation logic in middleware/auth.py across 3 files — 47 additions, 12 deletions. The fix addresses the token expiry bug that was causing intermittent 401 errors in production. Code reviewed and approved by @mike.",
    url: "https://github.com/team/repo/pull/247",
    triggered_by: "Hey Quorum, who touched the auth code this week?",
    timestamp: Date.now(),
    meeting_id: "demo",
    processing_steps: ["Connecting to repository...", "Fetching recent commits...", "Analyzing auth changes..."],
    visualization: {
      type: "bar_chart",
      caption: "Commits this week",
      data: [
        { label: "@sarah", value: 75, color: "#1D9E75" },
        { label: "@mike", value: 40, color: "#378ADD" },
        { label: "@alex", value: 15, color: "#BA7517" },
      ],
    },
  },
  {
    id: "card-2",
    event_type: "decision_logged",
    source: "meeting",
    title: "Decision: Migrate to OAuth 2.0 PKCE flow",
    summary: "Last Tuesday standup — the team agreed to move from session-based auth to OAuth 2.0 with PKCE. @sarah is leading implementation. Target deadline is end of sprint 14. This was prompted by the security audit findings from March 15th.",
    url: "https://notion.so/team/meeting-notes",
    triggered_by: "What did we decide about auth last week?",
    timestamp: Date.now(),
    meeting_id: "demo",
    processing_steps: ["Searching past meetings...", "Scanning decision log...", "Loading relevant context..."],
  },
  {
    id: "card-3",
    event_type: "action_taken",
    source: "asana",
    title: "Review auth middleware regression",
    summary: "Assigned to @alex in the Backend sprint board with context auto-filled from this meeting. Priority set to high. Due date: next Wednesday. The task description includes the relevant PR link and meeting context.",
    url: "https://app.asana.com/0/project/task",
    triggered_by: "Add that as a task for Alex",
    timestamp: Date.now(),
    meeting_id: "demo",
    badge: "Task created",
    processing_steps: ["Creating task in Asana...", "Auto-filling description...", "Assigning to @alex..."],
  },
  {
    id: "card-4",
    event_type: "context_surfaced",
    source: "chart",
    title: "Sprint velocity — last 4 sprints",
    summary: "Velocity is trending upward. Sprint 14 is on track with 34 of 42 story points completed. The auth migration accounts for 13 of those points. Team capacity was reduced in Sprint 12 due to holidays.",
    url: "https://jira.team.com/velocity",
    triggered_by: "Show me our sprint velocity",
    timestamp: Date.now(),
    meeting_id: "demo",
    processing_steps: ["Pulling sprint data...", "Calculating velocity...", "Rendering visualization..."],
    visualization: {
      type: "bar_chart",
      caption: "Story points completed",
      data: [
        { label: "Sprint 11", value: 55, color: "#3a3a3a" },
        { label: "Sprint 12", value: 68, color: "#555" },
        { label: "Sprint 13", value: 78, color: "#888" },
        { label: "Sprint 14", value: 85, color: "#1D9E75" },
      ],
    },
  },
];